languageCode = 'en-us'
title = 'min site'
baseurl = "/"

[params]
  custom_css = ["css/normalize.css", "css/style.css"]

[taxonomies]
  topic = 'topics'

# navbar pages
[[menu.main]]
  name = "Home"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

[[menu.main]]
  name = "Topics"
  url = "topics/"
  weight = 3
